version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '3001:3000'
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3000/api
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '3000:3000'
